Algoritmo "consumo"

var

   media, distancia, quantidadeGasolina : real
   

inicio

      escreva("Digite a distância percorrida: ")
      leia(distancia)
      escreva("Digite a quantidade de gaslina gasta: ")
      leia(quantidadeGasolina)
      
      
                              media <- distancia / quantidadeGasolina
                              
                              escreval("A média de combustível gasto é: ", media)
                              



Fimalgoritmo