Algoritmo "idades"

var

nome1, nome2: caractere
idade1, idade2 : inteiro


media : real

inicio


      escreva("Digite seu nome: ")
      leia(nome1)
      escreval("Digite sua idade: ")
      leia(idade1)
      escreva("Digite seu nome: ")
      leia(nome2)
      escreval("Digite sua idade: ")
      leia(idade2)
      
                  media <-  (idade1 + idade2) / 2
                  
                  escreval("A média de idades é: ", media)



Fimalgoritmo