Algoritmo "troco"

var

   produto, dinheiro, troco : real
   quantidade: inteiro


inicio

      escreva("Digite o valor do produto: ")
      leia(produto)
      escreva("Digite a quantidade comprada: ")
      leia(quantidade)
      escreva("Digite o valor recebido em dinheiro: ")
      leia(dinheiro)
      
                    troco <- dinheiro - produto
                    
                    escreval("O troco é: ", troco)



Fimalgoritmo